
OPENFOODFACTS_URL = 'https://fr.openfoodfacts.org'
OPENFOODFACTS_PAGE_SIZE = 100
OPENFOODFACTS_CATEGORIES = ('pates-a-tartiner-aux-noisettes', )

DATABASE_HOST = '127.0.0.1'
DATABASE_PORT = 5432
DATABASE_USER = 'postgres'
DATABASE_PASSWORD = '123456'
DATABASE_NAME = 'openfoodfact'

