
OPENFOODFACTS_URL = 'https://fr.openfoodfacts.org'
OPENFOODFACTS_PAGE_SIZE = 100
OPENFOODFACTS_CATEGORIES = ('sodas-au-cola', 'cremes-fraiches', )

LIMIT_CATEGORY_ITEMS = 10
LIMIT_PRODUCT_ITEMS = 10
