-- MySQL Script generated by MySQL Workbench
-- Wed Sep 30 08:41:30 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema openfoodfact
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema openfoodfact
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openfoodfact` DEFAULT CHARACTER SET utf8 ;
USE `openfoodfact` ;

-- -----------------------------------------------------
-- Table `openfoodfact`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`brands` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `quantity` VARCHAR(255) NULL DEFAULT NULL,
  `link` VARCHAR(2048) NULL DEFAULT NULL,
  `nutriscore` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `code` (`code` ASC) VISIBLE,
  INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`product_brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`product_brands` (
  `product_id` INT(11) NOT NULL,
  `brand_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `brand_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `brand_id` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `product_brands:brand_id`
    FOREIGN KEY (`brand_id`)
    REFERENCES `openfoodfact`.`brands` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `product_brands:product`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfact`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`product_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`product_categories` (
  `product_id` INT(11) NOT NULL,
  `category_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `category_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_categories:category_id`
    FOREIGN KEY (`category_id`)
    REFERENCES `openfoodfact`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_categories:product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfact`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`stores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`product_stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`product_stores` (
  `product_id` INT(11) NOT NULL,
  `store_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `store_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `store_id` (`store_id` ASC) VISIBLE,
  CONSTRAINT `product_stores:brand_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `openfoodfact`.`stores` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `product_stores:product`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfact`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `openfoodfact`.`product_substitute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `openfoodfact`.`product_substitute` (
  `product_id` INT(11) NOT NULL,
  `substitute_product_id` INT(11) NOT NULL,
  PRIMARY KEY (`product_id`, `substitute_product_id`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `substitute_product_id` (`substitute_product_id` ASC) VISIBLE,
  CONSTRAINT `product_substitute:product_id`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfact`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `product_substitute:substitute_product_id`
    FOREIGN KEY (`substitute_product_id`)
    REFERENCES `openfoodfact`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
